### PR TITLE
Support for Cbor/SenML via KeyMaps

### PR DESCRIPTION
**Pull request by mattaylor**
KeyMaps have been introduce as an option defining an object that will be used to remap properties of source Objects and Maps to short form equivalents - including integers for more efficient encoding. 
The principle driver for this feature is to support `application/senml+cbor`content-encoding as defined in https://datatracker.ietf.org/doc/html/rfc8428#section-6 for use in LWM2M application (see http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#7-4-7-0-747-SenML-CBOR)

Records are also supported in conjunction with keyMaps, but these are disabled by default when keyMaps are specified as the the use of the two features together has not yet been optimized and is currently less efficient than using just KeyMaps without Records.

```JavaScript
import { Encoder } from 'cbor-x'
const data = [ 
	{ bn: '/3303/0/5700', bt: 1278887, v: 35.5 },
	{ t: 10, v: 34 },
	{ t: 20, v: 33 },
	{ t: 30, v: 32 },
	{ t: 40, v: 31 },
	{ t: 50, v: 30 } 
]

let senmlKeys = { bs: -6, bv: -5, bu: -4, bt: -3, bn: -2, n: 0, u: 1, v: 2, vs: 3, t: 6, ut: 7, vd: 8 }
let senmlEncoder = new Encoder({ keyMap: senmlKeys })
let basicEncoder = new Ecoder()
let senmlCbor = senmlEncoder.encode(data)
let basicCbor = basicEncoder.encode(data)
console.log('Senml cbor size:', senmlCbor.length) // 77
console.log('basic cbor size:', basicCbor.length) // 90
assert.deepEqual(senmlEncoder.decode(senmlCbor), data)

```

### CODE REVIEW

**Comment by kriszyp** [comment]
Wow, this is pretty impressive, nice work. I'll take a further look at this and hopefully get it merged soon.

**Comment by mattaylor** [comment]
There are currently two alternative implementations. You can call encode/decode as per examples and set keyMap to the keys that should be remapped or alternatively you can call mapEncode / mapDecode on encoders and use _keyMap to define the keys to be mapped. I added this to explore optimizations as suggested by some tests where the keys were mapped outside of the encode / decode. Comparison of these approaches are in `/assets/test-keymap.txt` which is generated by a test script in `/tests/test-keymap.js`. I think the current implementation is prob good enough, and id like to remove the alternative code path, but you might have some ideas on other optimizations.

**Comment by kriszyp** [comment]
To make sure I understand SenML correctly, the key mappings are never sent as part of the message or stream, they are always considered out-of-band and should be agreed upon by both parties in the communication ahead of time?

**Comment by mattaylor** [comment]
Senml is basically a  Json schema with 8 or so tags defined.  Cbor,/senml is an encoding  of senml as cbor  where numeric map keys are used instead of strings.  
I have just generalized this idea by supporting any substitution of Json keys when encoding to and decoding from cbor, where such mappings are known in advance and agreed out of hand by both parties

**Pull request merged**
